<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\ezygo.Core\ezyGo.Core.csproj" />
    <ProjectReference Include="..\..\Core\ezyGo.EntityFrameworkCore\ezyGo.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\ezyGo.Admin.Storage\ezyGo.Admin.Storage.csproj" />
  </ItemGroup>

</Project>
