// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ezyGo.Admin.Storage.Sql;

#nullable disable

namespace ezyGo.Admin.Storage.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20251120133256_CreateTrainStationTable")]
    partial class CreateTrainStationTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ezyGo.Admin.Storage.Entities.TrainStation", b =>
                {
                    b.Property<int>("TrainStationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainStationId"));

                    b.Property<string>("TrainStationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainStationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainStationId");

                    b.ToTable("TrainStations");
                });

            modelBuilder.Entity("ezyGo.Admin.Storage.Entities.TrainStation", b =>
                {
                    b.OwnsOne("ezyGo.Admin.Storage.Entities.Geo", "Geo", b1 =>
                        {
                            b1.Property<int>("TrainStationId")
                                .HasColumnType("int");

                            b1.Property<int>("Latitude")
                                .HasColumnType("int");

                            b1.Property<int>("Longitude")
                                .HasColumnType("int");

                            b1.HasKey("TrainStationId");

                            b1.ToTable("TrainStations");

                            b1.WithOwner()
                                .HasForeignKey("TrainStationId");
                        });

                    b.Navigation("Geo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
