// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ezyGo.Admin.Storage.Sql;

#nullable disable

namespace ezyGo.Admin.Storage.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20251126093848_Bus-BusCompanyRelationShip")]
    partial class BusBusCompanyRelationShip
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ezyGo.Admin.Storage.Entities.BusCompanyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("BusCompanies");
                });

            modelBuilder.Entity("ezyGo.Admin.Storage.Entities.BusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusCompanyEntityId")
                        .HasColumnType("int");

                    b.Property<string>("BusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusRegNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BusType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalCapacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusCompanyEntityId");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("ezyGo.Admin.Storage.Entities.BusStationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusStations");
                });

            modelBuilder.Entity("ezyGo.Admin.Storage.Entities.TrainStation", b =>
                {
                    b.Property<int>("TrainStationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainStationId"));

                    b.Property<string>("TrainStationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainStationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainStationId");

                    b.ToTable("TrainStations");
                });

            modelBuilder.Entity("ezyGo.Admin.Storage.Entities.BusEntity", b =>
                {
                    b.HasOne("ezyGo.Admin.Storage.Entities.BusCompanyEntity", "Company")
                        .WithMany("Buses")
                        .HasForeignKey("BusCompanyEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ezyGo.Admin.Storage.Entities.BusStationEntity", b =>
                {
                    b.OwnsOne("ezyGo.Admin.Storage.Entities.Geo", "Geo", b1 =>
                        {
                            b1.Property<int>("BusStationEntityId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("BusStationEntityId");

                            b1.ToTable("BusStations");

                            b1.WithOwner()
                                .HasForeignKey("BusStationEntityId");
                        });

                    b.Navigation("Geo")
                        .IsRequired();
                });

            modelBuilder.Entity("ezyGo.Admin.Storage.Entities.TrainStation", b =>
                {
                    b.OwnsOne("ezyGo.Admin.Storage.Entities.Geo", "Geo", b1 =>
                        {
                            b1.Property<int>("TrainStationId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("TrainStationId");

                            b1.ToTable("TrainStations");

                            b1.WithOwner()
                                .HasForeignKey("TrainStationId");
                        });

                    b.Navigation("Geo")
                        .IsRequired();
                });

            modelBuilder.Entity("ezyGo.Admin.Storage.Entities.BusCompanyEntity", b =>
                {
                    b.Navigation("Buses");
                });
#pragma warning restore 612, 618
        }
    }
}
