<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>158550e0-0657-4cad-8608-577efbab99f6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="2.10.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ezyGo.Platform.Domain\ezyGo.Platform.Domain.csproj" />
    <ProjectReference Include="..\..\..\Core\ezyGo.PdfGenerator\ezyGo.PdfGenerator.csproj" />
    <ProjectReference Include="..\..\..\Core\ezyGo.Core.ServiceClients\ezyGo.Core.ServiceClients.csproj" />
  </ItemGroup>

</Project>
